def gerar_tabela_markdown_pass_fail(entrada):
    linhas = entrada.split("\n")
    funcoes_status = []
    for linha in linhas:
        if "[PASS]" in linha or "[FAIL]" in linha:
            status, funcao = linha.strip().split(" ", 1)
            status = status.replace("[", "").replace("]", "")
            nome_funcao = funcao.split("(")[0]
            funcoes_status.append((nome_funcao, status))

    tabela_markdown = "| Função | Status |\n"
    tabela_markdown += "|--------|--------|\n"

    for funcao, status in funcoes_status:
        tabela_markdown += f"| {funcao} | {status} |\n"

    return tabela_markdown


entrada = """[RUNNING] proveFail_TransferUnderBalancej(address,uint256)
   [PASS] proveFail_TransferUnderBalancej(address,uint256)
[RUNNING] prove_ZeroAddressHasNoToken()
   [PASS] prove_ZeroAddressHasNoToken()
[RUNNING] prove_TokenReceiverCanTransferFromTotalBalance(address,address,uint256)
   [PASS] prove_TokenReceiverCanTransferFromTotalBalance(address,address,uint256)
[RUNNING] prove_TransferFromNoFees(address,address,address,uint256)
   [PASS] prove_TransferFromNoFees(address,address,address,uint256)
[RUNNING] prove_MintZeroTokens(address)
   [PASS] prove_MintZeroTokens(address)
[RUNNING] proveFail_TransferFromUnderBalancei(address,address,uint256)
   [PASS] proveFail_TransferFromUnderBalancei(address,address,uint256)
[RUNNING] prove_TransferZeroAmount(address,address)
   [PASS] prove_TransferZeroAmount(address,address)
[RUNNING] prove_TokenReceiverCanTransferFromTotalBalanceZero(address,address,address)
   [PASS] prove_TokenReceiverCanTransferFromTotalBalanceZero(address,address,address)
[RUNNING] prove_AllowanceUpdatedAfterBurn(address,address,uint256)
   [PASS] prove_AllowanceUpdatedAfterBurn(address,address,uint256)
[RUNNING] prove_Approve(address,uint256)
   [PASS] prove_Approve(address,uint256)
[RUNNING] prove_SelfApproveAndTransferFromOwnAccount(address,address,uint256)
   [PASS] prove_SelfApproveAndTransferFromOwnAccount(address,address,uint256)
[RUNNING] prove_SelfTransferZeroAmountAllowed(address)
   [PASS] prove_SelfTransferZeroAmountAllowed(address)
[RUNNING] prove_TransferFromDecreasesAllowance(address,address,address,uint256)
   [PASS] prove_TransferFromDecreasesAllowance(address,address,address,uint256)
[RUNNING] prove_BurnSameAccount(address,uint256)
   [PASS] prove_BurnSameAccount(address,uint256)
[RUNNING] prove_TransferFrom(address,address,uint256,uint256)
   [PASS] prove_TransferFrom(address,address,uint256,uint256)
[RUNNING] prove_TransferFromZeroAmount(address,address,address)
   [PASS] prove_TransferFromZeroAmount(address,address,address)
[RUNNING] proveFail_TransferFromZeroAddress(address,address,uint256)
   [PASS] proveFail_TransferFromZeroAddress(address,address,uint256)
[RUNNING] prove_SelfTransferPositiveAmountAllowed(address,uint256)
   [PASS] prove_SelfTransferPositiveAmountAllowed(address,uint256)
[RUNNING] proveFail_BurnUnderBalance(address,uint256)
   [PASS] proveFail_BurnUnderBalance(address,uint256)
[RUNNING] proveFail_TransferFromAllowanceReachesZero(address,address,address,uint256,uint256)
   [PASS] proveFail_TransferFromAllowanceReachesZero(address,address,address,uint256,uint256)
[RUNNING] prove_MultipleTransfersAllowed(address,address,uint256,uint256)
   [PASS] prove_MultipleTransfersAllowed(address,address,uint256,uint256)
[RUNNING] proveFail_MintToZeroAddress(uint256)
   [PASS] proveFail_MintToZeroAddress(uint256)
[RUNNING] prove_ApproveNonZeroAmount(address,address,uint256)
   [PASS] prove_ApproveNonZeroAmount(address,address,uint256)
[RUNNING] prove_SelfApprovePositiveAmount(address,uint256)
   [PASS] prove_SelfApprovePositiveAmount(address,uint256)
[RUNNING] prove_TransferFromDoesNotUpdateOtherBalances(address,address,address,address,uint256)
   [PASS] prove_TransferFromDoesNotUpdateOtherBalances(address,address,address,address,uint256)
[RUNNING] proveFail_TransferFromZeroAddressForMSGSender(address,address,uint256)
   [PASS] proveFail_TransferFromZeroAddressForMSGSender(address,address,uint256)
[RUNNING] prove_MsgSenderCanRetrieveOtherBalance(address,uint256)
   [PASS] prove_MsgSenderCanRetrieveOtherBalance(address,uint256)
[RUNNING] prove_SelfApproveAndTransferFromOwnAccountZeroAmountAllowed(address,address)
   [PASS] prove_SelfApproveAndTransferFromOwnAccountZeroAmountAllowed(address,address)
[RUNNING] prove_Mint(address,uint256)
   [PASS] prove_Mint(address,uint256)
[RUNNING] proveFail_ApproveZeroAddress(address,uint256)
   [PASS] proveFail_ApproveZeroAddress(address,uint256)
[RUNNING] proveFail_TransferToZeroAddress(address,uint256)
   [PASS] proveFail_TransferToZeroAddress(address,uint256)
[RUNNING] proveFail_BurnUnderSupply(address,uint256)
   [PASS] proveFail_BurnUnderSupply(address,uint256)
[RUNNING] proveFail_ApproveFromZeroAddress(address,uint256)
   [PASS] proveFail_ApproveFromZeroAddress(address,uint256)
[RUNNING] prove_MultipleTransfersOfZeroAmountAllowed(address,address,uint8)
   [PASS] prove_MultipleTransfersOfZeroAmountAllowed(address,address,uint8)
[RUNNING] proveFail_ApproveZeroAddressForMSGSender(address,uint256)
   [PASS] proveFail_ApproveZeroAddressForMSGSender(address,uint256)
[RUNNING] prove_TransferDoesNotUpdateOtherBalances(address,address,address,uint256)
   [PASS] prove_TransferDoesNotUpdateOtherBalances(address,address,address,uint256)
[RUNNING] prove_BurnZeroTokens(address)
   [PASS] prove_BurnZeroTokens(address)
[RUNNING] prove_SelfApproveZeroAmountAllowed(address)
   [PASS] prove_SelfApproveZeroAmountAllowed(address)
[RUNNING] prove_MsgSenderCanRetrieveOwnBalance(uint256)
   [PASS] prove_MsgSenderCanRetrieveOwnBalance(uint256)
[RUNNING] prove_MsgSenderCanTransferTotalBalance(address,address,uint256)
   [PASS] prove_MsgSenderCanTransferTotalBalance(address,address,uint256)
[RUNNING] prove_BurnDifferentAccount(address,uint256,address,uint256)
   [PASS] prove_BurnDifferentAccount(address,uint256,address,uint256)
[RUNNING] prove_MsgSenderCanTransferTotalBalanceZero(address,address)
   [PASS] prove_MsgSenderCanTransferTotalBalanceZero(address,address)
[RUNNING] proveFail_TransferFromUnderBalance(address,address,uint256)
   [PASS] proveFail_TransferFromUnderBalance(address,address,uint256)
[RUNNING] prove_ConsecutiveApprovePositiveToPositive(address,address,uint256,uint256)
   [PASS] prove_ConsecutiveApprovePositiveToPositive(address,address,uint256,uint256)
[RUNNING] proveFail_BurnFromZeroAddress(uint256)
   [PASS] proveFail_BurnFromZeroAddress(uint256)
[RUNNING] prove_MultipleTransferFromAllowed(address,address,address,uint256,uint256)
   [PASS] prove_MultipleTransferFromAllowed(address,address,address,uint256,uint256)
[RUNNING] proveFail_TransferFromZeroAddress(address,uint256)
   [PASS] proveFail_TransferFromZeroAddress(address,uint256)
[RUNNING] proveFail_TransferUnderBalance(address,uint256)
   [PASS] proveFail_TransferUnderBalance(address,uint256)
[RUNNING] prove_Transfer(address,uint256,uint256)
   [PASS] prove_Transfer(address,uint256,uint256)
[RUNNING] prove_IncreaseAllowance(address,uint256)
   [PASS] prove_IncreaseAllowance(address,uint256)
[RUNNING] prove_BalanceUpdatedAfterBurn(address,address,uint256)
   [PASS] prove_BalanceUpdatedAfterBurn(address,address,uint256)
[RUNNING] prove_ApproveZeroAmount(address,address)
   [PASS] prove_ApproveZeroAmount(address,address)
[RUNNING] proveFail_TransferZeroAmountToZeroAddressReverts(address)
   [PASS] proveFail_TransferZeroAmountToZeroAddressReverts(address)
[RUNNING] proveFail_TransferFromToZeroAddress33(address,address,uint256)
   [PASS] proveFail_TransferFromToZeroAddress33(address,address,uint256)
[RUNNING] prove_DecreaseAllowance(address,uint256)
   [PASS] prove_DecreaseAllowance(address,uint256)
[RUNNING] prove_ApproveMaxAmount(address,address)
   [PASS] prove_ApproveMaxAmount(address,address)
[RUNNING] prove_BurnFromNonZeroAddress(address,uint256)
   [PASS] prove_BurnFromNonZeroAddress(address,uint256)
[RUNNING] proveFail_TransferFromZeroAmountToZeroAddressReverts(address,address)
   [PASS] proveFail_TransferFromZeroAmountToZeroAddressReverts(address,address)
[RUNNING] prove_MultipleTransferFromsOfZeroAmountAllowed(address,address,address,uint8)
   [PASS] prove_MultipleTransferFromsOfZeroAmountAllowed(address,address,address,uint8)
[RUNNING] proveFail_MintOverflow(address)
   [PASS] proveFail_MintOverflow(address)
[RUNNING] proveFail_ApproveToZeroAddress(address,uint256)
   [PASS] proveFail_ApproveToZeroAddress(address,uint256)"""

# Gerando a tabela em Markdown considerando 'PASS' e 'FAIL'
tabela = gerar_tabela_markdown_pass_fail(entrada)
print(tabela)
